# Generated by Django 2.2.12 on 2020-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiki_id', models.CharField(max_length=10)),
                ('kiki_name', models.CharField(max_length=30)),
                ('keito', models.CharField(max_length=30)),
                ('settibasho', models.CharField(max_length=30)),
                ('juyodo', models.CharField(max_length=1)),
            ],
        ),
    ]
