# Generated by Django 2.2.12 on 2020-04-20 00:33

import django.core.validators
from django.db import migrations, models
import kiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('kiki', '0002_auto_20200420_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiki',
            name='nensu',
            field=models.IntegerField(default=1, validators=[kiki.models.check_nensu]),
        ),
        migrations.AlterField(
            model_name='kiki',
            name='juyodo',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-D]*$', 'A～Dが範囲です')]),
        ),
    ]
