# Generated by Django 2.2.12 on 2020-04-20 03:00

import django.core.validators
from django.db import migrations, models
import kiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('kiki', '0003_auto_20200420_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiki',
            name='juyodo',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-D]*$', 'A～Dが範囲です')], verbose_name='重要度'),
        ),
        migrations.AlterField(
            model_name='kiki',
            name='keito',
            field=models.CharField(max_length=30, verbose_name='系統'),
        ),
        migrations.AlterField(
            model_name='kiki',
            name='kiki_id',
            field=models.CharField(max_length=10, verbose_name='機器ID'),
        ),
        migrations.AlterField(
            model_name='kiki',
            name='kiki_name',
            field=models.CharField(max_length=30, verbose_name='機器名称'),
        ),
        migrations.AlterField(
            model_name='kiki',
            name='nensu',
            field=models.IntegerField(default=1, validators=[kiki.models.check_nensu], verbose_name='耐用年数'),
        ),
        migrations.AlterField(
            model_name='kiki',
            name='settibasho',
            field=models.CharField(max_length=30, verbose_name='系統'),
        ),
    ]
